services:
  bf4db-bot:
    build:
      context: .
      args:
        VERSION: ${VERSION:-dev}
    image: ghcr.io/the-eduardo/bf4db-discord-bot:latest
    container_name: bf4-search-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
